Feature/add details module
MyDanchik/AVBY pull request #2
Opened 2023-12-23 21:30 UTC by MyDanchik

https://github.com/MyDanchik/AVBY/assets/99731538/ba12e3ca-6bf1-4c34-8a2a-5dd41478fdcd

2023-12-28 16:07 UTC, mishamorochko requested changes
Нужно исправить комментарии и можно мержить

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/Cell/ButtonTableViewCell.swift
> +    weak var presentingViewController: UIViewController?
VC в ячейке не должен быть

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/Cell/ButtonTableViewCell.swift
> +        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { _ in print("ok")}))
Алерт не тут должен показываться. Ячейка сообщает через делегат VC что что-то произошло, а уже VC у себя решает то делать (например отобразить алерт)

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/Cell/DescriptionTableViewCell.swift
> +    @IBOutlet var optionsStackView: UIStackView!
все private

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/Cell/DescriptionTableViewCell.swift
> +class DescriptionTableViewCell: UITableViewCell {
final

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/Cell/DetailsTableViewCell.swift
> +    @IBOutlet weak var conteinerView: UIView!
private

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/Cell/DetailsTableViewCell.swift
> +class DetailsTableViewCell: UITableViewCell {
final

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/ViewControlles/DetailsViewController.swift
> +    var receivedNameText: String?
private

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/ViewControlles/DetailsViewController.swift
> +class DetailsViewController: UIViewController {
final

2023-12-28 16:07 UTC, mishamorochko commented on AVBY/ViewControlles/SearchViewController.swift
> +        vc.receivedNameText = "\(name)"
Стоит просто передать в vc модель, и уже внутри VC все задавать в ui компоненты

2023-12-29 08:13 UTC, MyDanchik commented on AVBY/Cell/DescriptionTableViewCell.swift
> +    @IBOutlet var optionsStackView: UIStackView!
исправил

2023-12-29 08:17 UTC, MyDanchik commented on AVBY/Cell/DescriptionTableViewCell.swift
> +class DescriptionTableViewCell: UITableViewCell {
исправил

2023-12-29 08:17 UTC, MyDanchik commented on AVBY/Cell/DetailsTableViewCell.swift
> +    @IBOutlet weak var conteinerView: UIView!
исправил

2023-12-29 08:22 UTC, MyDanchik commented on AVBY/ViewControlles/DetailsViewController.swift
> +class DetailsViewController: UIViewController {
исправил

2023-12-29 11:02 UTC, MyDanchik commented on AVBY/ViewControlles/SearchViewController.swift
> +        vc.receivedNameText = "\(name)"
исправил

2023-12-29 11:03 UTC, MyDanchik commented on AVBY/ViewControlles/DetailsViewController.swift
> +    var receivedNameText: String?
этого уже нет

2023-12-29 11:36 UTC, MyDanchik commented on AVBY/Cell/ButtonTableViewCell.swift
> +        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { _ in print("ok")}))
исправил

2023-12-29 11:36 UTC, MyDanchik commented on AVBY/Cell/ButtonTableViewCell.swift
> +    weak var presentingViewController: UIViewController?
исправил

2024-01-04 19:53 UTC, merged